// Auto-generated by YDWS-CodingBank tools/export_course_js.py
// Do not edit manually unless you know what you are doing.

const course = {
  "code": "JSA00",
  "title": "基礎練習2",
  "type": "programming",
  "mode": "learning",
  "description": "",
  "source": {
    "project": "YDWS-CodingBank",
    "generatedAt": "2026-08-01T13:28:18+08:00",
    "sourceCsv": "data\\problem_bank_master_complete.csv",
    "version": "PB05-4B"
  },
  "tasks": [
    {
      "id": "A-08-0",
      "title": "查找最大值",
      "problemTitle": "查找最大值",
      "courseCode": "JSA00",
      "courseName": "基礎練習2",
      "role": "challenge",
      "blocklyFit": "中",
      "requiresGreenFlag": true,
      "description": "老師進行成績統計，老師輸入每位同學的成績，請你寫一個程式找出最高分。\n\n輸入第一行是整數 N，代表有 N 筆成績\n\n第二行輸入 N 個數字，數字間以空白間隔\n\n程式輸出最大值。\n這樣的練習可以幫助你處理一串資料，並找出其中的最大值。",
      "inputDescription": "",
      "outputDescription": "",
      "statement": {
        "description": "老師進行成績統計，老師輸入每位同學的成績，請你寫一個程式找出最高分。\n\n輸入第一行是整數 N，代表有 N 筆成績\n\n第二行輸入 N 個數字，數字間以空白間隔\n\n程式輸出最大值。\n這樣的練習可以幫助你處理一串資料，並找出其中的最大值。",
        "input": "",
        "output": ""
      },
      "examples": [
        {
          "input": "3\n9 6 8",
          "output": "9",
          "explanation": "第一行輸入3，表示有3個數字要輸入\n第二行輸入9 6 8三個數字序列\n程式運算輸出最大值9"
        },
        {
          "input": "6\n99 12 129 16 8",
          "output": "129",
          "explanation": "第一行輸入6，表示有6個數字要輸入\n第二行輸入99 12 129 16 8 3六個數字序列\n程式運算輸出最大值129"
        }
      ],
      "testCases": [
        {
          "input": "3\n9 6 8",
          "expectedOutput": "9",
          "output": "9",
          "score": 10,
          "hidden": false
        },
        {
          "input": "6\n99 12 129 16 8 3",
          "expectedOutput": "129",
          "output": "129",
          "score": 10,
          "hidden": false
        },
        {
          "input": "5\n89 15 47 0 56",
          "expectedOutput": "89",
          "output": "89",
          "score": 10,
          "hidden": false
        },
        {
          "input": "1\n25",
          "expectedOutput": "25",
          "output": "25",
          "score": 10,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "",
        "flags": [],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "迴圈與累計"
        ],
        "subConcepts": [
          "重複運算"
        ],
        "algorithm": [
          "迭代"
        ],
        "dataStructure": [],
        "syntax": [
          "for",
          "while",
          "累加變數"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "A-08-1",
      "title": "查找最大值、最小值",
      "problemTitle": "查找最大值、最小值",
      "courseCode": "JSA00",
      "courseName": "基礎練習2",
      "role": "challenge",
      "blocklyFit": "中",
      "requiresGreenFlag": true,
      "description": "老師進行成績統計，老師輸入每位同學的成績，請你寫一個程式找出最高分及最低分。\n\n輸入第一行是整數 N，代表有 N 筆成績\n\n第二行輸入 N 個數字，數字間以空白間隔\n\n程式輸出最大值及最小值。\n這樣的練習可以幫助你處理一串資料，並同時找出其中的最大值、最小值。",
      "inputDescription": "",
      "outputDescription": "",
      "statement": {
        "description": "老師進行成績統計，老師輸入每位同學的成績，請你寫一個程式找出最高分及最低分。\n\n輸入第一行是整數 N，代表有 N 筆成績\n\n第二行輸入 N 個數字，數字間以空白間隔\n\n程式輸出最大值及最小值。\n這樣的練習可以幫助你處理一串資料，並同時找出其中的最大值、最小值。",
        "input": "",
        "output": ""
      },
      "examples": [
        {
          "input": "3\n9 6 8",
          "output": "9\n6",
          "explanation": "第一行輸入3，表示有3個數字要輸入\n第二行輸入9 6 8三個數字序列\n程式運算輸出最大值9，最小值6"
        },
        {
          "input": "6\n99 12 129 16 8 3",
          "output": "129\n3",
          "explanation": "第一行輸入6，表示有6個數字要輸入\n第二行輸入99 12 129 16 8 3六個數字序列\n程式運算輸出最大值129，最小值3"
        }
      ],
      "testCases": [
        {
          "input": "3\n9 6 8",
          "expectedOutput": "9 6",
          "output": "9 6",
          "score": 10,
          "hidden": false
        },
        {
          "input": "6\n99 12 129 16 8 3",
          "expectedOutput": "129 3",
          "output": "129 3",
          "score": 10,
          "hidden": false
        },
        {
          "input": "5\n89 15 47 0 56",
          "expectedOutput": "89 0",
          "output": "89 0",
          "score": 10,
          "hidden": false
        },
        {
          "input": "1\n25",
          "expectedOutput": "25 25",
          "output": "25 25",
          "score": 10,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "",
        "flags": [],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "迴圈與累計"
        ],
        "subConcepts": [
          "重複運算"
        ],
        "algorithm": [
          "迭代"
        ],
        "dataStructure": [],
        "syntax": [
          "for",
          "while",
          "累加變數"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "A-09-0",
      "title": "判斷質數",
      "problemTitle": "判斷質數",
      "courseCode": "JSA00",
      "courseName": "基礎練習2",
      "role": "challenge",
      "blocklyFit": "中",
      "requiresGreenFlag": true,
      "description": "質數是大於 1 且只能被 1 和自己整除的數字。\n請寫一個程式，輸入一個整數 N，判斷它是否為質數。\n\n若是質數輸出 Yes，否則輸出 No。\n\n這題訓練你使用條件與迴圈判斷。",
      "inputDescription": "",
      "outputDescription": "",
      "statement": {
        "description": "質數是大於 1 且只能被 1 和自己整除的數字。\n請寫一個程式，輸入一個整數 N，判斷它是否為質數。\n\n若是質數輸出 Yes，否則輸出 No。\n\n這題訓練你使用條件與迴圈判斷。",
        "input": "",
        "output": ""
      },
      "examples": [
        {
          "input": "1",
          "output": "No",
          "explanation": "第一行輸入1\n電腦運算判斷1不是質數\n程式運算輸出No"
        },
        {
          "input": "2",
          "output": "Yes",
          "explanation": "第一行輸入2\n電腦運算判斷2是質數\n程式運算輸出Yes"
        },
        {
          "input": "7",
          "output": "Yes",
          "explanation": "第一行輸入7\n電腦運算判斷7是質數\n程式運算輸出Yes"
        },
        {
          "input": "6",
          "output": "No",
          "explanation": "第一行輸入6\n電腦運算判斷6可被2整除，不是質數\n程式運算輸出No"
        }
      ],
      "testCases": [
        {
          "input": "1",
          "expectedOutput": "No",
          "output": "No",
          "score": 10,
          "hidden": false
        },
        {
          "input": "2",
          "expectedOutput": "Yes",
          "output": "Yes",
          "score": 10,
          "hidden": false
        },
        {
          "input": "1007",
          "expectedOutput": "No",
          "output": "No",
          "score": 10,
          "hidden": false
        },
        {
          "input": "997",
          "expectedOutput": "Yes",
          "output": "Yes",
          "score": 10,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "",
        "flags": [],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "數學運算與數論"
        ],
        "subConcepts": [
          "整數性質"
        ],
        "algorithm": [
          "枚舉",
          "輾轉相除"
        ],
        "dataStructure": [],
        "syntax": [
          "取餘數",
          "迴圈"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "A-09-1",
      "title": "找因數",
      "problemTitle": "找因數",
      "courseCode": "JSA00",
      "courseName": "基礎練習2",
      "role": "challenge",
      "blocklyFit": "中",
      "requiresGreenFlag": true,
      "description": "因數是指一個整數能被另一整數「整除」時，這個「除數」就是「被除數」的因數。\n\n0不是任何整數的因數。1是所有整數的因數。\n\n請寫一個程式，輸入一個整數 N，請找出N所有的因數。\n\n所有因數以空白符號間格\n\n這題訓練你使用條件與迴圈判斷。",
      "inputDescription": "",
      "outputDescription": "",
      "statement": {
        "description": "因數是指一個整數能被另一整數「整除」時，這個「除數」就是「被除數」的因數。\n\n0不是任何整數的因數。1是所有整數的因數。\n\n請寫一個程式，輸入一個整數 N，請找出N所有的因數。\n\n所有因數以空白符號間格\n\n這題訓練你使用條件與迴圈判斷。",
        "input": "",
        "output": ""
      },
      "examples": [
        {
          "input": "12",
          "output": "1 2 3 4 6 12",
          "explanation": "第一行輸入12\n程式輸出12所有因數1 2 3 4 6 12"
        },
        {
          "input": "39",
          "output": "1 3 13 39",
          "explanation": "第一行輸入39\n程式輸出39所有因數1 3 13 39"
        }
      ],
      "testCases": [
        {
          "input": "56",
          "expectedOutput": "1 2 4 7 8 14 28 56",
          "output": "1 2 4 7 8 14 28 56",
          "score": 10,
          "hidden": false
        },
        {
          "input": "37",
          "expectedOutput": "1 37",
          "output": "1 37",
          "score": 10,
          "hidden": false
        },
        {
          "input": "78",
          "expectedOutput": "1 2 3 6 13 26 39 78",
          "output": "1 2 3 6 13 26 39 78",
          "score": 10,
          "hidden": false
        },
        {
          "input": "88",
          "expectedOutput": "1 2 4 8 11 22 44 88",
          "output": "1 2 4 8 11 22 44 88",
          "score": 10,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "",
        "flags": [],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "數學運算與數論"
        ],
        "subConcepts": [
          "整數性質"
        ],
        "algorithm": [
          "枚舉",
          "輾轉相除"
        ],
        "dataStructure": [],
        "syntax": [
          "取餘數",
          "迴圈"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "A-10-0",
      "title": "多科成績計算",
      "problemTitle": "多科成績計算",
      "courseCode": "JSA00",
      "courseName": "基礎練習2",
      "role": "challenge",
      "blocklyFit": "中",
      "requiresGreenFlag": true,
      "description": "小明參加了數學、英文、自然...等多科的段考，老師希望能快速算出總分與平均分數，並判斷是否及格。\n\n請設計程式，輸入多科的成績，計算總分與平均。\n\n第一行輸入共有幾科\n\n第二行依序輸入各科成績，科成績之間以空白間隔\n\n計算總分，平均成績以四捨五入取整數\n\n如果平均分數大於等於 60，就輸出「及格」，否則輸出「不及格」。\n\n這題可以訓練你如何處理多筆資料的加總、平均計算，並搭配條件判斷。",
      "inputDescription": "",
      "outputDescription": "",
      "statement": {
        "description": "小明參加了數學、英文、自然...等多科的段考，老師希望能快速算出總分與平均分數，並判斷是否及格。\n\n請設計程式，輸入多科的成績，計算總分與平均。\n\n第一行輸入共有幾科\n\n第二行依序輸入各科成績，科成績之間以空白間隔\n\n計算總分，平均成績以四捨五入取整數\n\n如果平均分數大於等於 60，就輸出「及格」，否則輸出「不及格」。\n\n這題可以訓練你如何處理多筆資料的加總、平均計算，並搭配條件判斷。",
        "input": "",
        "output": ""
      },
      "examples": [
        {
          "input": "3\n80 70 90",
          "output": "240\n80\n及格",
          "explanation": "第一行輸入3，表示後面會有3個數字輸入\n第二行輸入80 70 90，經過計算後\n總分180、平均80、及格"
        },
        {
          "input": "6\n50 41 60 55 70 65",
          "output": "341\n57\n不及格",
          "explanation": "第一行輸入6，表示後面會有3個數字輸入\n第二行輸入50 41 60 55 70 65，經過計算後\n程式輸出總分341、平均57、不及格"
        }
      ],
      "testCases": [
        {
          "input": "3\n20 60 90",
          "expectedOutput": "170 57 不及格",
          "output": "170 57 不及格",
          "score": 10,
          "hidden": false
        },
        {
          "input": "6\n50 41 60 55 70 65",
          "expectedOutput": "341 57 不及格",
          "output": "341 57 不及格",
          "score": 10,
          "hidden": false
        },
        {
          "input": "5\n80 70 75 85 90",
          "expectedOutput": "400 80 及格",
          "output": "400 80 及格",
          "score": 10,
          "hidden": false
        },
        {
          "input": "1\n55",
          "expectedOutput": "55 55 不及格",
          "output": "55 55 不及格",
          "score": 10,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "",
        "flags": [],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "字串處理"
        ],
        "subConcepts": [
          "字元統計與格式判斷"
        ],
        "algorithm": [],
        "dataStructure": [
          "字串"
        ],
        "syntax": [
          "字串",
          "索引",
          "len"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "A-11-0",
      "title": "計算字元出現次數",
      "problemTitle": "計算字元出現次數",
      "courseCode": "JSA00",
      "courseName": "基礎練習2",
      "role": "challenge",
      "blocklyFit": "中",
      "requiresGreenFlag": true,
      "description": "請設計程式，輸入一個字串，並輸入一個英文字母輸出該字母在字串中出現的次數。\n\n這樣的練習可以訓練你操作字串與統計。",
      "inputDescription": "",
      "outputDescription": "",
      "statement": {
        "description": "請設計程式，輸入一個字串，並輸入一個英文字母輸出該字母在字串中出現的次數。\n\n這樣的練習可以訓練你操作字串與統計。",
        "input": "",
        "output": ""
      },
      "examples": [
        {
          "input": "banana\na",
          "output": "3",
          "explanation": "第一行輸入banana\n第二行輸入字元a\n程式運算比對a出現3次\n程式輸出3"
        },
        {
          "input": "student\nt",
          "output": "2",
          "explanation": "第一行輸入student\n第二行輸入字元t\n程式運算比對t出現2次\n程式輸出2"
        }
      ],
      "testCases": [
        {
          "input": "Goodmoning\no",
          "expectedOutput": "3",
          "output": "3",
          "score": 10,
          "hidden": false
        },
        {
          "input": "ChaiYiCity\ni",
          "expectedOutput": "3",
          "output": "3",
          "score": 10,
          "hidden": false
        },
        {
          "input": "announcement\nn",
          "expectedOutput": "4",
          "output": "4",
          "score": 10,
          "hidden": false
        },
        {
          "input": "experimen\ne",
          "expectedOutput": "3",
          "output": "3",
          "score": 10,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "",
        "flags": [],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "字串處理"
        ],
        "subConcepts": [
          "字元統計與格式判斷"
        ],
        "algorithm": [],
        "dataStructure": [
          "字串"
        ],
        "syntax": [
          "字串",
          "索引",
          "len"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "A-12-0",
      "title": "簡易密碼轉換",
      "problemTitle": "簡易密碼轉換",
      "courseCode": "JSA00",
      "courseName": "基礎練習2",
      "role": "challenge",
      "blocklyFit": "中",
      "requiresGreenFlag": true,
      "description": "小明設計了一種簡單的密碼環密碼規則：將每個字母向後移二個字母（z 變 b）。\n\n密碼環：abcdefghijklmnopqrstuvwxyz\n\n請寫一個程式，輸入一個英文單字，輸出轉換後的字串。\n\n這樣的練習訓練你字元處理與條件轉換。",
      "inputDescription": "",
      "outputDescription": "",
      "statement": {
        "description": "小明設計了一種簡單的密碼環密碼規則：將每個字母向後移二個字母（z 變 b）。\n\n密碼環：abcdefghijklmnopqrstuvwxyz\n\n請寫一個程式，輸入一個英文單字，輸出轉換後的字串。\n\n這樣的練習訓練你字元處理與條件轉換。",
        "input": "",
        "output": ""
      },
      "examples": [
        {
          "input": "banana",
          "output": "dcpcpc",
          "explanation": "第一行輸入banana\n程式運算，將字串往後移2個位置加密\n程式輸出dcpcpc"
        },
        {
          "input": "student",
          "output": "uvwfgpv",
          "explanation": "第一行輸入student\n程式運算，將字串往後移2個位置加密\n程式輸出uvwfgpv"
        }
      ],
      "testCases": [
        {
          "input": "goodmoning",
          "expectedOutput": "iqqfoqpkpi",
          "output": "iqqfoqpkpi",
          "score": 10,
          "hidden": false
        },
        {
          "input": "chaiyicity",
          "expectedOutput": "ejckakekva",
          "output": "ejckakekva",
          "score": 10,
          "hidden": false
        },
        {
          "input": "announcement",
          "expectedOutput": "cppqwpegogpv",
          "output": "cppqwpegogpv",
          "score": 10,
          "hidden": false
        },
        {
          "input": "experimen",
          "expectedOutput": "gzrgtkogp",
          "output": "gzrgtkogp",
          "score": 10,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "",
        "flags": [],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "字串處理"
        ],
        "subConcepts": [
          "字元統計與格式判斷"
        ],
        "algorithm": [],
        "dataStructure": [
          "字串"
        ],
        "syntax": [
          "字串",
          "索引",
          "len"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    },
    {
      "id": "A-13-0",
      "title": "二數的最大公因數",
      "problemTitle": "二數的最大公因數",
      "courseCode": "JSA00",
      "courseName": "基礎練習2",
      "role": "challenge",
      "blocklyFit": "中",
      "requiresGreenFlag": true,
      "description": "小明上學時，不太會找最大公因數，請寫個程式幫他找一下\n輸入二個整數，請計算這二個數字的最大公因數",
      "inputDescription": "輸入2行\n第一行輸入第1個整數N\n第二行輸入地2個整數M\n程式運算找出二數的最大公因數並輸出",
      "outputDescription": "",
      "statement": {
        "description": "小明上學時，不太會找最大公因數，請寫個程式幫他找一下\n輸入二個整數，請計算這二個數字的最大公因數",
        "input": "輸入2行\n第一行輸入第1個整數N\n第二行輸入地2個整數M\n程式運算找出二數的最大公因數並輸出",
        "output": ""
      },
      "examples": [
        {
          "input": "9\n6",
          "output": "3",
          "explanation": "第一行輸入9，\n第二行輸入6，\n程式輸出6、9二個數的最大公因數3"
        },
        {
          "input": "30\n72",
          "output": "6",
          "explanation": "第一行輸入30，\n第二行輸入72\n程式輸出30，72二個數的最大公因數6"
        }
      ],
      "testCases": [
        {
          "input": "12\n6",
          "expectedOutput": "6",
          "output": "6",
          "score": 10,
          "hidden": false
        },
        {
          "input": "34\n52",
          "expectedOutput": "2",
          "output": "2",
          "score": 10,
          "hidden": false
        },
        {
          "input": "24\n18",
          "expectedOutput": "6",
          "output": "6",
          "score": 10,
          "hidden": false
        },
        {
          "input": "1\n8",
          "expectedOutput": "1",
          "output": "1",
          "score": 10,
          "hidden": false
        }
      ],
      "starterXml": "",
      "review": {
        "needsManualReview": false,
        "risk": "",
        "flags": [],
        "note": "",
        "exportDecision": "輸出"
      },
      "tags": {
        "mainConcepts": [
          "數學運算與數論"
        ],
        "subConcepts": [
          "整數性質"
        ],
        "algorithm": [
          "枚舉",
          "輾轉相除"
        ],
        "dataStructure": [],
        "syntax": [
          "取餘數",
          "迴圈"
        ],
        "math": [],
        "context": []
      },
      "restrictions": {
        "requiredBlocks": [],
        "disabledBlocks": []
      }
    }
  ]
};

export default course;
